[project]
name = "automatic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
    "pymysql>=1.1.2",
    "pypdf>=6.4.0",
    "flask>=3.0.0",
    "psycopg2-binary>=2.9.11",
]
